language: node_js
node_js:
  - "4.0.0"

addons:
  firefox: "39.0"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: 
  - "npm install"
  - "npm install bower -g"
  - "bower install"
  - "gulp test"